### ISSUE TITLE
RSVP page not mobile friendly

### ISSUE THREAD

**Issue by andromria** [andromria/wedding_site#14]
On mobile, when the hamburger menu button is pressed, nothing seems to happen, resulting in the user being stuck on the RSVP page.

**Comment by TIMOTHYKTECH** [comment]
Sorry, i forgot to notate, I also made the logo/title of your site a link to the homepage and fixed the navigation bar a little.

**Comment by andromria** [comment]
Cool. Can we also add some kind of background image to the RSVP page so it's not blank?
